#!/usr/bin/env bash
# Renders core/gateway/envoy-gateway.yaml from the pinned upstream chart.
#
# Run from anywhere:  ./core/gateway/render.sh
#
# Why this is a script and not one helm command, two reasons:
#
#  1. The chart carries the Gateway API EXPERIMENTAL channel CRDs in Helm's
#     crds/ directory. Nothing in values.yaml can deselect them, because crds/
#     is not templated. ADR 0008 says standard channel only, and
#     core/gateway-api/crds.yaml installs the standard channel, so the rendered
#     output has every Gateway API CRD removed after rendering.
#
#  2. `helm template` against an oci:// chart prints "Pulled:" and "Digest:" on
#     STDOUT the first time it fetches the chart, and those two lines land
#     inside the manifest. It only happens on a cold chart cache, so the
#     corruption is intermittent. The chart is pulled to a temporary directory
#     first and rendered from there, which keeps stdout clean and also gives
#     the digest to record in the header.
set -euo pipefail

CHART="oci://docker.io/envoyproxy/gateway-helm"
VERSION="v1.9.1"
NAMESPACE="envoy-gateway-system"
RELEASE="eg"

cd "$(dirname "$0")/../.."
OUT="core/gateway/envoy-gateway.yaml"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

DIGEST="$(helm pull "$CHART" --version "$VERSION" --untar --untardir "$TMP" \
  | awk '/^Digest:/ {print $2}')"
[ -n "$DIGEST" ] || { echo "helm pull printed no digest" >&2; exit 1; }

helm template "$RELEASE" "$TMP/gateway-helm" \
  --namespace "$NAMESPACE" \
  --include-crds \
  --values core/gateway/envoy-gateway-values.yaml \
  | python3 core/gateway/strip-gatewayapi-crds.py \
  > "$TMP/rendered.yaml"

{
  echo "# Envoy Gateway ${VERSION}, rendered from ${CHART}"
  echo "# ${DIGEST}"
  echo "#"
  echo "# Generated by core/gateway/render.sh. Do NOT edit in place — change"
  echo "# core/gateway/envoy-gateway-values.yaml and render again, so this file"
  echo "# always matches a named chart version."
  echo "#"
  echo "# Every Gateway API CRD is stripped: the chart ships the EXPERIMENTAL"
  echo "# channel and ADR 0008 says standard only. The standard channel comes"
  echo "# from core/gateway-api/crds.yaml, which must be applied first."
  cat "$TMP/rendered.yaml"
} > "$OUT"

echo "wrote $OUT"
