apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteio

resources:
  - ../../base

images:
  - name: stevetosak/wasteio-bin-agent
    newTag: latest

replicas:
  - name: wasteio-bin-agent
    count: 5
