apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteio

resources:
- ../../base

images:
- name: stevetosak/wasteio-frontend
  newTag: alpha-6e6d34c4141625d12286d391eef177c660bfeb20
replicas:
- count: 1
  name: wasteio-frontend
