apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteio

resources:
- ../../base

images:
- name: stevetosak/wasteio-frontend
  newTag: alpha-9a6915a357c676f3cc687d38d86e38a85448d7b1
replicas:
- count: 1
  name: wasteio-frontend
