apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteio

resources:
- ../../base

images:
- name: stevetosak/wasteio-frontend
  newTag: alpha-b7ffd0a494467091c25683a158e54d81c5ba720d
replicas:
- count: 1
  name: wasteio-frontend
