apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doma

resources:
- ../../base

images:
- name: stevetosak/doma
  newTag: alpha-a1410e1068f9aec871aceb38d54b3ac2f0d90e17

replicas:
- count: 1
  name: doma
