apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doma

resources:
- ../../base

images:
- name: stevetosak/doma
  newTag: alpha-e67d514b95adb11d3876b92082cde068b05eae4c

replicas:
- count: 1
  name: doma
