apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doma

resources:
- ../../base

images:
- name: stevetosak/doma
  newTag: alpha-a96402e8da21bb53bbcad63d24c7bafa5224d891

replicas:
- count: 1
  name: doma
