apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaps-backend
  labels:
    app: imaps-backend
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: imaps-backend
  template:
    metadata:
      labels:
        app: imaps-backend
    spec:
      containers:
        - name: imaps-backend
          image: stevetosak/imaps-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: imaps-backend-config
            - secretRef:
                name: credentials

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
  strategy:
    type: "Recreate"
    