apiVersion: v1
data:
    DB_PASS: ENC[AES256_GCM,data:wO4uRdIT6ztV6IVZvuRW3eropUss913pm28F09cozyUln18G/aRVzXoXNLVwBIZqU3l87QaozlQ=,iv:o3g9R4sHsgmvipfiriHtcfSvblks9MSJu99XWQtbx/M=,tag:I8/9YsIlWYjUdIqNmEbZvQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:dDmpRSv17B4=,iv:KM0PA28rF1egrZfFrxOUPk6iFKWqekf+k1CbY2LIAXo=,tag:xaTsE1WUjl1lZX1jusRwfQ==,type:str]
    REDIS_PASS: ENC[AES256_GCM,data:Tu14pe5RLErq/xgVXCqm48L/RpwhobtfBwtvDbspZPR49r2/tD2dteQOLhG3U+tkulVmNfnDDtA=,iv:zKfPc1GuMdz+EgKgbRmuB/0/CEdsLAUPn17wzKo0sek=,tag:f/VV1xEB+VvxMm5o3+ACWw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: credentials
    namespace: authos
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dWtESUNkK3dGWWN0cWsw
            Mld0NGp2WHpoL2hvdC8yeTFUS0JGWDVMbDJRCjNUamJDTlJ2V1VOYlUzcHp4N2Mv
            dnJKSG11ZzZlaXRoTHEyaDRMaUxKeEEKLS0tIFFkaDJUTmJobjNlN3Q0ZkIySFJy
            Z0Z3aTdRcjl6Q1BsR2R0OGlQMzRmaUEK+vMaoCc+zgBecCcMcH2nDmkHLsUGwRTw
            Lcgo1CgSbiy9inIY/QJ2ITHtid7c4SCZbBknAvT0zrdxasCZ0cs/zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T18:56:02Z"
    mac: ENC[AES256_GCM,data:s9WQzLE2Q1R9wlGeX5zwmA8YDKkZOac4oaISsxc3qv8t26qugvI8KDSQlTpwdNUCLAfcZeXXUn1yAq6gBqpAS1VYpcrYsLc3mxv0g7y2E9aYSQzHNc0fxTVS6mDmRFLNqzpeJ4PZnh+QNqkqtRHQL4KZr46vzFCD4j7BeIE1kec=,iv:y0qIKfrRFdBlVI/dO8IZ+jqzd0010BhxNkELNn16nuo=,tag:fhmUjQuWrBfnORB0RDv3Ow==,type:str]
    version: 3.13.3
