apiVersion: v1
data:
    KEYSTORE_PASS: ENC[AES256_GCM,data:En0n8G3Gd+vAKj6XEQurnF1tFimcNeyKHv24PnEf9sXiRhifNYtIwfyCBAQ=,iv:tdtHUhcQ1qYy7aYMgUdBAVIacxolkADqNqaqFmbpG2Q=,tag:btrmuqixxlxi09y7xtYQQQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keystore-pass
    namespace: authos
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R0FFV1ZJcUNVaVllMUxx
            MmIxaXByMlZnUzhnbUR3N1NWTkRaWEo5MmlZCkJUTEFpYVJZVkFYUkFndi8zNncy
            Z0thRCtTOHFnS2FZZ0h2Q0MvV1g0VTgKLS0tIG10Sk4rTUJJeWw0ZVNlc3NCdTNh
            TkhLZ3hZMGtkQ0FVQ3pvc3JrNU8xdzQKYGxPB3lAVf284jc+GXSHLw4cLeNNwWeH
            X87qU+c/UiX6t/Mzf8LTNX+n0QDwAD/DXYxanR9Py/h7nPnan801qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T18:55:33Z"
    mac: ENC[AES256_GCM,data:/1/gn09n5Zti9U63R7oFeOKbDyLTF7EmeX8aNgAsOwxKva6yV4TBtW20wcKTKamI4G5UuMTobPFkWOzo7PFKCu22anFP6ntn3f3KY4sJo/UCD8mX42iTCTMld370KTd4MJ8VDJ/oZBocHWe6nCiMW5jyZ1JeGiS6nM1kVFRhjZ4=,iv:cpj8Hjgtap30KugSmzxI2dfTMqjnDNum9k8GgmX93jo=,tag:e4j3aoEF6urxuVcqg3QsFw==,type:str]
    version: 3.13.3
