apiVersion: v1
data:
    KEYSTORE_PASS: ENC[AES256_GCM,data:En0n8G3Gd+vAKj6XEQurnF1tFimcNeyKHv24PnEf9sXiRhifNYtIwfyCBAQ=,iv:tdtHUhcQ1qYy7aYMgUdBAVIacxolkADqNqaqFmbpG2Q=,tag:btrmuqixxlxi09y7xtYQQQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keystore-pass
    namespace: authos
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYXR3dmtRbm1UNUx1L3hr
            em85Q3l0aXJRT0NZQU5iUkRsQ3pqUlVHc1hVClNWZytidC93OXVQeWRhT29TQWJZ
            Y0psQmIxL0pzZXdYYWN3U1RXWEp2aWsKLS0tIFlLUUFYVFlCdDIvanIrV2txVHBz
            NkhaWkVhcG5LSm9RZXlUVzRCM3hjcGcKA/QStltbYDliiZH81T4TJoWLp81okGwi
            5wmtYirRH9T0wric6PZjcKoQNL6fQhm0YHocNjZLiHgefvN+XP5Yow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVemJRYWFyQS9GbWN4ZEhK
            RWFiV3FhOWl1ZXYxYTRFbHB1RDZSdGRsR1NvCnZzTDRiY1o1VWs3dHpzbWdWNUJx
            MVBjeHVuSjgxYmFWN0cycnFvd2NINFkKLS0tIHdsM3NaU2FVMjRIakRkODBRZXl0
            Q3EyQTBWaElsang5Z2pVSGZJYmYyTGMKzOjJEr28fSDFXkFOSuvLtNEe9tiGyd+q
            SmHgdK8jiGFn0boLH5By6Mgpr7LxFc40gMt0XV+z6TADCL9f/ruhPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age167896gaqg05ht7eaa78z2jhk4p9gxnyfep8ft3f8cvu8wh3dd3hscv3n8j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T18:55:33Z"
    mac: ENC[AES256_GCM,data:/1/gn09n5Zti9U63R7oFeOKbDyLTF7EmeX8aNgAsOwxKva6yV4TBtW20wcKTKamI4G5UuMTobPFkWOzo7PFKCu22anFP6ntn3f3KY4sJo/UCD8mX42iTCTMld370KTd4MJ8VDJ/oZBocHWe6nCiMW5jyZ1JeGiS6nM1kVFRhjZ4=,iv:cpj8Hjgtap30KugSmzxI2dfTMqjnDNum9k8GgmX93jo=,tag:e4j3aoEF6urxuVcqg3QsFw==,type:str]
    version: 3.13.3
