#!/usr/bin/env bash
# Renders core/argocd/argocd.yaml from the pinned upstream chart.
#
# Run from anywhere:  ./core/argocd/render.sh
#
# Same shape as core/gateway/render.sh and core/cert-manager/render.sh, and for
# the same reason: `helm template` against an oci:// chart prints "Pulled:" and
# "Digest:" on STDOUT the first time it fetches the chart, and those two lines
# would land inside the manifest. It only happens on a cold chart cache, so the
# corruption would be intermittent. The chart is pulled to a temporary
# directory first, which keeps stdout clean and also gives the digest to record
# in the header.
#
# ADR 0008 needs two things of ArgoCD that are plain chart values, which is why
# this is a render and not a byte-for-byte upstream manifest: `--insecure` on
# argocd-server, and a Service port that advertises `kubernetes.io/h2c`. Both
# would otherwise be hand edits to a generated file.
#
# The render is deterministic. No template in this chart calls randAlphaNum,
# genCA or uuidv4 — with one exception, noted in argocd-values.yaml: setting
# `configs.secret.argocdServerAdminPassword` renders a timestamp from `now`.
# That value is not set.
set -euo pipefail

CHART="oci://ghcr.io/argoproj/argo-helm/argo-cd"
VERSION="10.9.2"
NAMESPACE="argocd"
RELEASE="argocd"

cd "$(dirname "$0")/../.."
OUT="core/argocd/argocd.yaml"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

DIGEST="$(helm pull "$CHART" --version "$VERSION" --untar --untardir "$TMP" \
  | awk '/^Digest:/ {print $2}')"
[ -n "$DIGEST" ] || { echo "helm pull printed no digest" >&2; exit 1; }

APP_VERSION="$(awk '/^appVersion:/ {print $2}' "$TMP/argo-cd/Chart.yaml")"

helm template "$RELEASE" "$TMP/argo-cd" \
  --namespace "$NAMESPACE" \
  --include-crds \
  --values core/argocd/argocd-values.yaml \
  > "$TMP/rendered.yaml"

{
  echo "# ArgoCD ${APP_VERSION}, chart ${VERSION}, rendered from ${CHART}"
  echo "# ${DIGEST}"
  echo "#"
  echo "# Generated by core/argocd/render.sh. Do NOT edit in place — change"
  echo "# core/argocd/argocd-values.yaml and render again, so this file always"
  echo "# matches a named chart version."
  echo "#"
  echo "# Apply with --server-side. The applicationsets CRD alone is about"
  echo "# 23,000 lines, far over the 256 KiB annotation limit a client-side"
  echo "# apply needs."
  cat "$TMP/rendered.yaml"
} > "$OUT"

echo "wrote $OUT (ArgoCD ${APP_VERSION}, chart ${VERSION})"
