apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:8layDvgDCGqTuqyHJ3Pnvl4Z/xmuMLbZBvyUXaSz5hh2GqgV54YJLKYW+ls=,iv:VljM7wRkzN36ZkZaYa5Tq2U+pYE+Nxb06wL/ertR3UI=,tag:04t3Wy7Iy503z0yIpyBXig==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Gm+0xq2GQAcT1f4tEDeVuhVt8xbdbAi1gEY5VEAvgiNQW5kIM/DotwQaE84KeJpRPZDIEeROvHyPv1Qg12rjpfXzVeR5DtauZuedzNPi+F71wTH5R4wdgQ==,iv:mzQ3WsqQ8wf8FqkSjToYXM5c0PIMeqRWnGRr7g6BPAw=,tag:rxrIjtKcp6caY+pPYzlsyA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: r2-backup-credentials
    namespace: pg-cluster
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVzM4RmhGblFrdEZBeVdt
            aHpLZHBqelorNWdBalZSRlMzdlJUYzY3VUJJCkdwd29kNmxlY2ozb28xMXd0b1N5
            RXZsNlZoY2xVVmpmK1VPWkZJQzVYL0kKLS0tIDZ0eVlsYUcxdGRuOWhhN2JqZUMv
            aUhEQXJ1UGlCMWFqVk5JeXh2U1RSQzgKH/OL6nANbBg1zEJ4w3Ey3r/QwXkv2GfP
            jtdfwGMmSkrjJ5uhWc0hfsAQJc23Fw98Xr69PTN7FcefqSwtLFdndg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR1FvalphVGhQaVhrZVY2
            eVFrSzVHZTRGc3FTdkdsOUxDMCsrNTVaaWo4CldlWEFyOSsxWEFscUg3SWZva1ps
            VFgyay9sdkFVWTlKVUhMWmE3NHhkaE0KLS0tIDV0R1ZOVFczaG5FQzl5WjRiRnN5
            cFY0NlVTZWtQSHRBK1dXbzRHQjBNZTgKAbrKyn2cPXaWHNURT66mi77bi/SUKp1K
            ggmwaAd/mnH59UzmdlRSwGSnEtKCb5CoREPBwflo+yuOSp53GVs2+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age167896gaqg05ht7eaa78z2jhk4p9gxnyfep8ft3f8cvu8wh3dd3hscv3n8j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T22:26:26Z"
    mac: ENC[AES256_GCM,data:vPCR2bBbGdmtg68xWK0olk6Jkk3g7rYhFLsrRLeCOJPTT2kvjgZ0LVEH1qicUJgdoFi2sQCx4slCHEa0BUIrmkN4aIrSy+5Fk1WVlOVSXpXbaowvvyXf+iLjYU21QpUa8jQecf5LQN7ViBNDADgIn5X+N7EDzYpmFUTKq9XLodg=,iv:LCVj/HBJ9TmHDdJg/W40a018KQRiQmUxtXTwwAavGzU=,tag:ZyXnzs0uh1875bB8+WgGCA==,type:str]
    version: 3.13.3
