apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imaps

resources:
  - ../../base

images:
  - name: stevetosak/imaps-backend
    newTag: 1.0.0
replicas:
  - count: 3
    name: imaps-backend
