apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:8a88Z6E7JvTWvndRO7n3t38/LCQ757Zc1VU5nVwpQv4xk4g/+YuTO/IIy54=,iv:DGDBOLqyXaQAnKyMaojc4J+QELtTvOobsUEtn1Lg36g=,tag:w8+g7qH/qdOY8nYSJpFyMw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Cf1LqY8xfiquCHWQZss2pq+IiFlzDYq5oGvZp2qi5LbDKISDr0ucK2E8fwfNHCMvY0XIWq9W6ep3nfKlRiMZcF8x+z/3/A/ffxhMJEJL1mIk6VsJHUQYug==,iv:pkkTOn01O5U5Rb+U0MTqUwg2hNVktW2ALoEhECLHhc8=,tag:SMA8pr2Qck8lk/RsXvL6iA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: r2-drill-results-credentials
    namespace: pg-drill
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd1U4UVBKRG5LQm13U0dG
            Sm1LbVVGOXRyNVhNVWFxOEJUYVB2c091dG5NCmx0Nk5zRGRTUUl0dWtXdjdIcXl4
            REZLajhJZ0dCM1I2dlJ2SEZNN3RPREUKLS0tIElRdUx5TE10b0ZBc0dnS0ZRZE01
            TS9xZnZJVnFLSjRxTDVpNmdTaEszNlUK/4mwvKcWG0NsLdQUsfKt82koPE8PzDeu
            YlbP3Gyh8nvFQrZot5MsPIcbBrcuD6eIXYUyKonNjr2zcxUnw7ihAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcS9wN0hSZ3ZLUGNGSUVr
            L3h1Q09PT1Y4a2l2NFFqMDRKREROSkVhbEJRCmtWMEJZMFhVS3BMdC9sSStmRUZ4
            Z3Y1QU85WEF1VUM0NkU4eFBVMnd4LzgKLS0tIFpSNVQ2RVhNTi9sYjZ4eDBpWnRP
            VHh3U3BjSXdtTXF5WnVlcG16ZHdkMVEKHft96ctKj4888RB+I48H7uGCccmnd7Mm
            VvH6y3DWM0xlvdKF3vo5OPobO57lvORRUFuLTi4qdVS2Rj5hIig2MA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age167896gaqg05ht7eaa78z2jhk4p9gxnyfep8ft3f8cvu8wh3dd3hscv3n8j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T23:42:15Z"
    mac: ENC[AES256_GCM,data:oZGfiPtK/eM6M4qm7OxNn9TsdUvhp4OnKkCStkPzWrc5GJuE5Hmkvb6TaDWuPfWvI0HiwlEtuRRQlQE1q2GQbxKa0gB/hEwKZGb2bmvaHqKHT7hrFxQDm9V63Ut4zxY7EjeodU4Dc2bQnHTvLkLOTFDcm/GZ2usn1ocn/V4Xp6o=,iv:E9nm8gl5+y5cCzs3y5XwkSXP0KU00XzuCRMpXsWm58k=,tag:XGssIie44gRXBh/WZvUzUw==,type:str]
    version: 3.13.3
