apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:HP/O9oZTtzdyWgHu6Tzabt2kXOUwu9b4fo4K+XeR9/7u/u0b1iL45Md73l4=,iv:eBCUQUOBlVq2tb3UkyQwiUG2IOZIhUhzi90xzTcIzFc=,tag:EZTlHBD9+JrdMfUCzBPnMQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:NrTCso0KFG5avFcoqv1OcPVeCcSiN/TEOPw/m5dCOCN8N4ftqALvRZkqQ8HKuOJRwjjonuaINRd45oWSpP68IOKGURKpMCh4hR+Hy8kZyswY0rRjKlsRyQ==,iv:hbitu+rkowSTsTj5NzSSAgLGOb4x+aqro7Ury+O6SNk=,tag:EwkbFIJs5RJOQiIb0tWCRw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: r2-readonly-credentials
    namespace: pg-drill
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRTZqbE16bWZTeDFUUmJm
            enZBL2thZXJGV3FZQ2tGaEVFbkZrdkNHZlRRCk9ESEptSkdsODZUNC9iRDFnWjcw
            b2hWeHFzK1duelR5VjhsbS9HSmxHMmcKLS0tIHpBYjVTQW1FeXJkVGNaQWJYOC9Q
            bldiL3VEMUFxSmJyOEJuamVLaFV2dHMKpnYnCTtAYDOifMkfP/lX8uGHzKUzTr/J
            KOLGet8MlfT76SvK/TMZix72QG6F7A3mezXZ8Gqdjfgx+Nfk9R5nBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFFjVTJDMmw2Njg0T0U0
            UjBSR1lCbXNIK0tEZlQwYy9mVDdOcUxkL0VNClRmYjhMQm10UFJBLzBDbmM2OHlO
            bHBmWG5NdjYweDJhQUZmVjVhbFl6cmsKLS0tIHNVSENKRGp0UWFjRE5BZ2xWZmJX
            QWU5M01PVzJmbjJ5cFBuTnBTWXVCWG8KHW6p95/m7WpBBqjODb1TTUvmZc81+p6C
            v0ATUTSP8VoqDKAbf4QglalPWADNF6p/iEJi4GjZkLREEgqpHmrO4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age167896gaqg05ht7eaa78z2jhk4p9gxnyfep8ft3f8cvu8wh3dd3hscv3n8j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T23:41:40Z"
    mac: ENC[AES256_GCM,data:62BhHcjQbNwgs8JbDSwciMDhv3YMDSTi/3OUgyyP0eEa4eIG3rbGO32E7Xy6O8ctYV3toltEewe+ibpS8QX1xt75DHtl004JmGpZ2ybAyBPcEWZIy6FX/4Kvw95+dsf9+R2YVA7VzPlhsk99wFqtRdzxNb0/8sNqCyRuzXQb+9o=,iv:jO0/N08sIm6m4hdX7tGUd2nEui1F3253YYCOBbO/RP8=,tag:wxQ0Ob2NcIxEMuncl8k+dg==,type:str]
    version: 3.13.3
