apiVersion: v1
data:
    BOT_TOKEN: ENC[AES256_GCM,data:vxOa4Tm0CzrPs7QzdGqMOPihDqPUqhQPEVSC1h68VKaIP814MnAk3kqS0gKZ5/zRFC+8lBcwb/bQDD+heKAfdA==,iv:x0wxSGVlOon0SDvNIwlHnvteVDoSr/etCEMy3UtKnRs=,tag:IhvneuVNWKhydqgzBHznsg==,type:str]
    CHAT_ID: ENC[AES256_GCM,data:HI5ZTYX0a24wq5xXUTbP2w==,iv:dplO84Q/uwxujSBSjovrWhYOqKmrEKSEEwCGnrpSt5g=,tag:tgpTxw4V+h8aCLY90a3VfA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: telegram
    namespace: pg-drill
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWUZmQXNMeUdTNHdzdUoy
            ajZJUEhkemdRU3BSU05paC80aWdMTzdMZFJjCnBRSU5nU2hXaVpXbzBLdGIrZ3lV
            QTFXcHlGcGx5aU9SWWUvR2J5dkM0NGcKLS0tIGNUdHNjRHcwS0puVkhhRHhlVDhU
            OStQby9LRW1QRGtsRXBwb2tvdlpZcGcKnJAFJ/UkKV/gQTfaDABsmicM9evNwLPC
            UH4QJcupSkMVkZjsEbJtIg8rgb/WuKYrseBtXtmZAlFh/l6AK+pjpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1djev7m4tq9z9lgrd8r3unhlzgzfkx3j6vz6dltu4rumqnnu7fq5q0aqtnd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbU11SCtsVUttRTZieGVC
            NTNOdmMwb0pBNHpLdC9EbVpRajk1MGthMDA0CmtyazhYd1RSVkRoZ2JsM2xuWjYw
            Y1ZoTWhLZzNPbDRIVzlXdnE2ejVZWmcKLS0tIG1vNzZzUFhZcTdBUEp1akpDODVI
            MHluc3lVK1dIWDdRSVhka2NXM1J3OEUKn+cXv8yks6YxZIWaWJbJYVWZXtckb4Z1
            EthYnbmp2JHpJTqz10R4kYPCIw+rogoduERbPZFLlNu3OjJvVN0kVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age167896gaqg05ht7eaa78z2jhk4p9gxnyfep8ft3f8cvu8wh3dd3hscv3n8j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T23:43:04Z"
    mac: ENC[AES256_GCM,data:s37MrTcxo4NB3IaY2XM3s1Xosr6KS1jSqKIrhd6wtCWkZjXQqtmXy6JDHFBtcds0BK299xzY71N91XjmqMpdWz2aDMrJoQWlsgaexSUhCZrWv6lBQyOPWx2lKNL0Tq+llujxsPpsTIeHWl2o0GWVKV0B8BA5Hj88unMvvDx/7aQ=,iv:htzqd45Ic901rmjXXQtMJK4FazujNDbE+XCxYIrGtEI=,tag:ur91owZdeCjkoUKDOdv+AQ==,type:str]
    version: 3.13.3
