apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
- ../../base
replicas:
- count: 1
  name: authos-ui

images:
- name: stevetosak/authos-ui
  newTag: alpha-138a853b9cf9a934b7bc3748047f2473b6c4693e
