apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
- ../../base
replicas:
- count: 1
  name: authos-ui

images:
- name: stevetosak/authos-ui
  newTag: alpha-79fd738af7d1e7c1244fdb6bbef2416afe0142f2
