apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
- ../../base

images:
- name: stevetosak/authos-api
  newTag: alpha-9aa49b8c19f6a96f8b84e9524e92329334a1084f
replicas:
- count: 1
  name: authos-api
