apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
- ../../base

images:
- name: stevetosak/authos-api
  newTag: alpha-11543db77f037fbd06dca3f0f47a77ef0f67e36f
replicas:
- count: 1
  name: authos-api
