apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authos

resources:
- ../../base

images:
- name: stevetosak/authos-api
  newTag: alpha-abdea13a6593ae7eb0d0516e04320d583f3a06dd
replicas:
- count: 1
  name: authos-api
