#!/usr/bin/env bash
# Renders core/cert-manager/cert-manager.yaml from the pinned upstream chart.
#
# Run from anywhere:  ./core/cert-manager/render.sh
#
# The chart is pulled to a temporary directory before rendering. `helm
# template` against an oci:// chart prints "Pulled:" and "Digest:" on STDOUT
# the first time it fetches the chart, and those lines would land inside the
# manifest. It only happens on a cold chart cache, so the corruption would be
# intermittent.
set -euo pipefail

CHART="oci://quay.io/jetstack/charts/cert-manager"
VERSION="v1.21.2"
NAMESPACE="cert-manager"
RELEASE="cert-manager"

cd "$(dirname "$0")/../.."
OUT="core/cert-manager/cert-manager.yaml"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

DIGEST="$(helm pull "$CHART" --version "$VERSION" --untar --untardir "$TMP" \
  | awk '/^Digest:/ {print $2}')"
[ -n "$DIGEST" ] || { echo "helm pull printed no digest" >&2; exit 1; }

helm template "$RELEASE" "$TMP/cert-manager" \
  --namespace "$NAMESPACE" \
  --include-crds \
  --values core/cert-manager/cert-manager-values.yaml \
  > "$TMP/rendered.yaml"

{
  echo "# cert-manager ${VERSION}, rendered from ${CHART}"
  echo "# ${DIGEST}"
  echo "#"
  echo "# Generated by core/cert-manager/render.sh. Do NOT edit in place —"
  echo "# change core/cert-manager/cert-manager-values.yaml and render again."
  echo "#"
  echo "# Needs the Gateway API CRDs to exist before it starts (ADR 0008)."
  cat "$TMP/rendered.yaml"
} > "$OUT"

echo "wrote $OUT"
