apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteio

resources:
- ../../base

images:
- name: stevetosak/wasteio-api
  newTag: alpha-0738a79b0270b20d83742eb81cfd288ef35553ab
replicas:
  - name: wasteio-api
    count: 1
