apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wasteio

resources:
  - ../../base

images:
  - name: stevetosak/wasteio-api
    newTag: latest
replicas:
  - name: wasteio-api
    count: 1
