apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imaps

resources:
- ../../base
replicas:
- count: 1
  name: imaps-frontend

images:
- name: stevetosak/imaps-frontend
  newTag: 1.0.0
