apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: authos
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: keystore
          mountPath: /etc/keystore
  volumes:
    - name: keystore
      secret:
        secretName: keystore
  restartPolicy: Never
